version: "2"

linters:
  default: standard
  enable:
  - depguard
  - dogsled
  - funlen
  - goconst
  - gocritic
  - gocyclo
  - revive
  - gosec
  - misspell
  - unconvert

  # default
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused

  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 60
    revive:
      rules:
      - name: exported
        disabled: true
    depguard:
      rules:
        main:
          deny:
          - pkg: golang.org/x/net/context
            desc: Use context package from stdlib
          - pkg: github.com/prometheus/common/log
            desc: Use structured logging
          - pkg: github.com/sirupsen/logrus
            desc: Use slog
  exclusions:
    rules:
    - path: _test\.go
      linters:
      - gomnd
    paths:
    - \.peg\.go
    - ".*ignored_.*.go$"
    - "generated.go$"
    - model_gen.go
    - vendor
    - ent
    - graph
